### ISSUE TITLE
locus: TEI-breaking change of content model

### ISSUE THREAD

**Issue by mjhawkins** [cambridge-collection/cdcp-schemata#28]
The content model of locus was changed to allow for `<hi>` within locus. As this is a TEI-breaking change, it should likely be implemented in the local Oxford version of the ODD rather than the core version.

**Comment by holfordm** [comment]
This is no longer TEI breaking, https://github.com/TEIC/TEI/issues/1628

**Comment by mjhawkins** [comment]
You're quite right. The original schema also added in `<g/>` but it's also there in TEI too. Those changes have therefore been removed from the schema (Commit 4a3aae10).
