### ISSUE TITLE
locus: ensuring that locus @from and @to match facs @n

### ISSUE THREAD

**Issue by eifionjones** [cambridge-collection/cdcp-schemata#5]
For the digital library/collections platform, the from and to attributes on locus need to point to a matching value in the n attribute on facsimile/surface. This is because the locus is turned into a link which brings up the relevant page when clicked.

Can we introduce a schematron rule that when facsimile/surface exist, from/to values on locus should match a n attribute on surface? This wouldn't affect records in the manuscript catalogues as they lack facsimile elements?

**Comment by mjhawkins** [comment]
Red (error) for digital platform.

Further discussion are required to determine if an error or warning (yellow) should appear elsewhere.

This rule should apply to all locus elements, not just those in msItem that are used when indexing/paginating the document by the CDCP.

**Comment by mjhawkins** [comment]
These attributes must match surface's n attribute.

Ensure facsimile exists for rule to fire

**Comment by mjhawkins** [comment]
Test has been added to the dp schema
